/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.config.EnumeratedProperties;
import java.util.LinkedList;
import java.util.List;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestEnumeratedProperties {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      EnumeratedProperties enumeratedProperties0 = new EnumeratedProperties();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add(".:a?&r`EZj~}");
      enumeratedProperties0.setEnumeratedProperty(".:a?&r`EZj~}", (List<String>) linkedList0);
      List<String> list0 = enumeratedProperties0.getEnumeratedProperty(".:a?&r`EZj~}");
      assertEquals("{.:a?&r`EZj~}.0=.:a?&r`EZj~}}", enumeratedProperties0.toString());
      assertEquals(false, list0.isEmpty());
  }

  @Test
  public void test1()  throws Throwable  {
      EnumeratedProperties enumeratedProperties0 = new EnumeratedProperties();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add(".:a?&r`EZj~}");
      enumeratedProperties0.setEnumeratedProperty(".:a?&r`EZj~}", (List<String>) linkedList0);
      assertEquals(1, enumeratedProperties0.size());
      
      LinkedList<String> linkedList1 = new LinkedList<String>();
      enumeratedProperties0.setEnumeratedProperty(".:a?&r`EZj~}", (List<String>) linkedList1);
      assertEquals(0, enumeratedProperties0.size());
  }
}
