/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.config.Configure;
import ghm.follow.gui.FollowAppAction;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestConfigure {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Configure.BooleanComboBox configure_BooleanComboBox0 = new Configure.BooleanComboBox("F7'K:FWGhC:x'V", "F7'K:FWGhC:x'V");
      configure_BooleanComboBox0.setValue(true);
      assertEquals(false, configure_BooleanComboBox0.isPaintingTile());
  }

  @Test
  public void test1()  throws Throwable  {
      Configure configure0 = new Configure((FollowApp) null);
      assertEquals(FollowAppAction.ActionContext.APP, configure0.getContext());
  }

  @Test
  public void test2()  throws Throwable  {
      Configure.BooleanComboBox configure_BooleanComboBox0 = new Configure.BooleanComboBox("F7@'K:FWGhC:x'V", "F7@'K:FWGhC:x'V");
      configure_BooleanComboBox0.setValue(false);
      assertEquals(false, configure_BooleanComboBox0.isFocusCycleRoot());
  }

  @Test
  public void test3()  throws Throwable  {
      Configure.BooleanComboBox configure_BooleanComboBox0 = new Configure.BooleanComboBox("O", "O");
      boolean boolean0 = configure_BooleanComboBox0.getValue();
      assertEquals(true, boolean0);
  }
}
