/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.gui.Edit;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestEdit {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Edit edit0 = new Edit((FollowApp) null);
      assertEquals(true, edit0.isEnabled());
  }
}
