/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.gui.ClearAll;
import ghm.follow.gui.FollowAppAction;
import ghm.follow.gui.PopupMenu;
import java.io.IOException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestPopupMenu {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PopupMenu popupMenu0 = new PopupMenu();
      ClearAll clearAll0 = new ClearAll((FollowApp) null);
      popupMenu0.addFollowAppAction((FollowAppAction) clearAll0);
      assertEquals(1, popupMenu0.getComponentCount());
      assertEquals(1, popupMenu0.countComponents());
  }
}
