/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.gui.About;
import ghm.follow.gui.FollowAppAction;
import ghm.follow.gui.Menu;
import javax.swing.Icon;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestMenu {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Menu menu0 = new Menu("xKQW!b", "xKQW!b", (Icon) null);
      About about0 = new About((FollowApp) null);
      menu0.addFollowAppAction((FollowAppAction) about0);
      assertEquals(1, menu0.getItemCount());
      assertEquals(0, menu0.getDisplayedMnemonicIndex());
  }

  @Test
  public void test1()  throws Throwable  {
      Menu menu0 = new Menu("3Bp&Pfr<Vs9]^AxLco", "3Bp&Pfr<Vs9]^AxLco");
      assertEquals(51, menu0.getMnemonic());
  }
}
