/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.gui.DndFileOpener;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetEvent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDndFileOpener {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DndFileOpener dndFileOpener0 = new DndFileOpener((FollowApp) null);
      dndFileOpener0.dragOver((DropTargetDragEvent) null);
  }

  @Test
  public void test1()  throws Throwable  {
      DndFileOpener dndFileOpener0 = new DndFileOpener((FollowApp) null);
      dndFileOpener0.dragScroll((DropTargetDragEvent) null);
  }

  @Test
  public void test2()  throws Throwable  {
      DndFileOpener dndFileOpener0 = new DndFileOpener((FollowApp) null);
      dndFileOpener0.dragExit((DropTargetEvent) null);
  }

  @Test
  public void test3()  throws Throwable  {
      DndFileOpener dndFileOpener0 = new DndFileOpener((FollowApp) null);
      dndFileOpener0.dropActionChanged((DropTargetDragEvent) null);
  }

  @Test
  public void test4()  throws Throwable  {
      DndFileOpener dndFileOpener0 = new DndFileOpener((FollowApp) null);
      dndFileOpener0.dragEnter((DropTargetDragEvent) null);
  }
}
