/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.gui.WhatIsThis;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestWhatIsThis {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      WhatIsThis whatIsThis0 = new WhatIsThis((FollowApp) null, "action.Open.name", "action.Open.name");
      // Undeclared exception!
      try {
        whatIsThis0.doClick();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
