/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.gui.FollowAppAction;
import ghm.follow.gui.ToolBar;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestToolBar {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ToolBar toolBar0 = new ToolBar();
      // Undeclared exception!
      try {
        toolBar0.addFollowAppAction((FollowAppAction) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
