/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.gui.LineTextUI;
import javax.swing.JComponent;
import javax.swing.JTextField;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestLineTextUI {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LineTextUI lineTextUI0 = new LineTextUI();
      assertNotNull(lineTextUI0);
      
      JTextField jTextField0 = new JTextField();
      lineTextUI0.installUI((JComponent) jTextField0);
      assertEquals((-1), lineTextUI0.selectedIndex);
      assertEquals(-1, lineTextUI0.getSelectedIndex());
  }

  @Test
  public void test1()  throws Throwable  {
      LineTextUI lineTextUI0 = new LineTextUI();
      assertNotNull(lineTextUI0);
      
      int int0 = lineTextUI0.getSelectedIndex();
      assertEquals((-1), int0);
  }
}
