/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.gui.Open;
import java.awt.event.ActionEvent;
import java.io.File;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOpen {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Open open0 = new Open((FollowApp) null);
      ActionEvent actionEvent0 = new ActionEvent((Object) "cellRenderer", 79, "cellRenderer", (long) 79, 79);
      // Undeclared exception!
      try {
        open0.actionPerformed(actionEvent0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      File file0 = new File("c3[", "c3[");
      Open open0 = new Open((FollowApp) null, file0);
      ActionEvent actionEvent0 = new ActionEvent((Object) "/mnt/fastdata/ac1gf/SF110/dist/41_follow/c3[/c3[", (-4), "/mnt/fastdata/ac1gf/SF110/dist/41_follow/c3[/c3[", (long) (-4), (-4));
      // Undeclared exception!
      try {
        open0.actionPerformed(actionEvent0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
