/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FileFollower;
import ghm.follow.io.FilteredDestination;
import ghm.follow.io.OutputDestination;
import ghm.follow.search.SearchEngine;
import java.io.File;
import java.util.List;
import javax.swing.JEditorPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FileFollowerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      File file0 = new File("LYx", "LYx");
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      FileFollower fileFollower0 = new FileFollower(file0, 0, 0, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      // Undeclared exception!
      try {
        fileFollower0.restart();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      FileFollower fileFollower0 = new FileFollower((File) null, 1, 1, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      // Undeclared exception!
      try {
        fileFollower0.stopAndWait();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      File file0 = new File("m:} >KZ\"Ls)Uw", "m:} >KZ\"Ls)Uw");
      OutputDestination[] outputDestinationArray0 = new OutputDestination[9];
      FileFollower fileFollower0 = new FileFollower(file0, 0, 0, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      JEditorPane jEditorPane0 = new JEditorPane();
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jEditorPane0, (SearchEngine) null, "m:} >KZ\"Ls)Uw", true);
      fileFollower0.removeOutputDestination((OutputDestination) filteredDestination0);
      assertEquals(0, fileFollower0.getLatency());
      assertEquals(0, fileFollower0.getBufferSize());
  }

  @Test
  public void test3()  throws Throwable  {
      File file0 = new File("m:} >KZ\"Ls)Uw", "m:} >KZ\"Ls)Uw");
      OutputDestination[] outputDestinationArray0 = new OutputDestination[9];
      FileFollower fileFollower0 = new FileFollower(file0, 0, 0, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      List<OutputDestination> list0 = fileFollower0.getOutputDestinations();
      assertEquals(0, fileFollower0.getLatency());
      assertEquals(0, fileFollower0.getBufferSize());
      assertNotNull(list0);
      assertEquals(9, list0.size());
  }

  @Test
  public void test4()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      FileFollower fileFollower0 = new FileFollower((File) null, (-694), (-694), outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      fileFollower0.isPaused();
      assertEquals(-694, fileFollower0.getLatency());
      assertEquals(-694, fileFollower0.getBufferSize());
  }

  @Test
  public void test5()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[1];
      FileFollower fileFollower0 = new FileFollower((File) null, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      fileFollower0.setLatency(0);
      assertEquals(0, fileFollower0.getLatency());
      assertEquals(32768, fileFollower0.getBufferSize());
  }

  @Test
  public void test6()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[5];
      FileFollower fileFollower0 = new FileFollower((File) null, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      fileFollower0.unpause();
      assertEquals(1000, fileFollower0.getLatency());
      assertEquals(false, fileFollower0.isPaused());
      assertEquals(32768, fileFollower0.getBufferSize());
  }

  @Test
  public void test7()  throws Throwable  {
      File file0 = new File("");
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      FileFollower fileFollower0 = new FileFollower(file0, 0, 0, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      boolean boolean0 = fileFollower0.addOutputDestination(outputDestinationArray0[1]);
      assertEquals(true, boolean0);
      assertEquals(0, fileFollower0.getBufferSize());
      assertEquals(0, fileFollower0.getLatency());
  }

  @Test
  public void test8()  throws Throwable  {
      File file0 = new File("");
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      FileFollower fileFollower0 = new FileFollower(file0, 0, 0, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      fileFollower0.isBeingFollowed();
      assertEquals(0, fileFollower0.getBufferSize());
      assertEquals(0, fileFollower0.getLatency());
  }

  @Test
  public void test9()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      FileFollower fileFollower0 = new FileFollower((File) null, (-694), (-694), outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      fileFollower0.setBufferSize((-694));
      assertEquals(-694, fileFollower0.getLatency());
      assertEquals(-694, fileFollower0.getBufferSize());
  }

  @Test
  public void test10()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      FileFollower fileFollower0 = new FileFollower((File) null, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      // Undeclared exception!
      try {
        fileFollower0.start();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test11()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[1];
      FileFollower fileFollower0 = new FileFollower((File) null, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      int int0 = fileFollower0.getBufferSize();
      assertEquals(32768, int0);
      assertEquals(1000, fileFollower0.getLatency());
  }

  @Test
  public void test12()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      FileFollower fileFollower0 = new FileFollower((File) null, (-694), (-694), outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      int int0 = fileFollower0.getLatency();
      assertEquals((-694), int0);
      assertEquals(-694, fileFollower0.getBufferSize());
  }

  @Test
  public void test13()  throws Throwable  {
      OutputDestination[] outputDestinationArray0 = new OutputDestination[5];
      FileFollower fileFollower0 = new FileFollower((File) null, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      fileFollower0.pause();
      assertEquals(true, fileFollower0.isPaused());
  }

  @Test
  public void test14()  throws Throwable  {
      FileFollower fileFollower0 = new FileFollower((File) null, (-1744), (-1744), (OutputDestination[]) null);
      assertNotNull(fileFollower0);
      
      FileFollower.Runner fileFollower_Runner0 = fileFollower0.new Runner();
      assertNotNull(fileFollower_Runner0);
      
      fileFollower_Runner0.run();
      assertEquals(-1744, fileFollower0.getLatency());
      assertEquals(-1744, fileFollower0.getBufferSize());
  }

  @Test
  public void test15()  throws Throwable  {
      File file0 = new File("");
      OutputDestination[] outputDestinationArray0 = new OutputDestination[2];
      JTextField jTextField0 = new JTextField();
      SearchEngine searchEngine0 = new SearchEngine(0);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jTextField0, searchEngine0, "", false);
      outputDestinationArray0[0] = (OutputDestination) filteredDestination0;
      outputDestinationArray0[1] = (OutputDestination) filteredDestination0;
      FileFollower fileFollower0 = new FileFollower(file0, 0, 0, outputDestinationArray0);
      assertNotNull(fileFollower0);
      
      FileFollower.Runner fileFollower_Runner0 = fileFollower0.new Runner();
      assertNotNull(fileFollower_Runner0);
      
      fileFollower_Runner0.runAction();
      assertEquals(0, fileFollower0.getBufferSize());
      assertEquals(0, fileFollower0.getLatency());
  }
}
