/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.gui.FollowAppAction;
import ghm.follow.gui.Pause;
import java.awt.Window;
import java.util.List;
import javax.swing.ImageIcon;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FollowAppEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        FollowApp.centerWindowInScreen((Window) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = FollowApp.class;
      ImageIcon imageIcon0 = FollowApp.getIcon(class0, "action.ClearHighlights.accelerator");
      assertEquals(-1, imageIcon0.getIconHeight());
  }

  @Test
  public void test2()  throws Throwable  {
      FollowApp followApp0 = FollowApp.getInstance();
      assertNull(followApp0);
  }

  @Test
  public void test3()  throws Throwable  {
      Class<?> class0 = List.class;
      ImageIcon imageIcon0 = FollowApp.getIcon(class0, "action.Exit.name");
      assertNull(imageIcon0);
  }

  @Test
  public void test4()  throws Throwable  {
      Pause pause0 = new Pause((FollowApp) null);
      assertEquals(FollowAppAction.ActionContext.SINGLE_FILE, pause0.getContext());
  }
}
