/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.io.FilteredDestination;
import ghm.follow.search.SearchEngine;
import javax.swing.JPasswordField;
import javax.swing.text.JTextComponent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FilteredDestinationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JPasswordField jPasswordField0 = new JPasswordField("[{fQ$Z/Rr.F", 1372);
      SearchEngine searchEngine0 = new SearchEngine(1372);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jPasswordField0, searchEngine0, "[{fQ$Z/Rr.F", false);
      filteredDestination0.print("[{fQ$Z/Rr.F");
  }
}
