/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.io.FilteredDestination;
import ghm.follow.io.JTextComponentDestination;
import ghm.follow.search.SearchEngine;
import javax.swing.JEditorPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class JTextComponentDestinationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JTextField jTextField0 = new JTextField();
      SearchEngine searchEngine0 = new SearchEngine(2);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jTextField0, searchEngine0, "MDHw+n", false);
      boolean boolean0 = filteredDestination0.autoPositionCaret();
      assertEquals(false, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      JEditorPane jEditorPane0 = new JEditorPane(".>^'W<-Tp68G", ".>^'W<-Tp68G");
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jEditorPane0, false);
      jTextComponentDestination0.setJTextComponent((JTextComponent) jEditorPane0);
      assertEquals(false, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test2()  throws Throwable  {
      JPasswordField jPasswordField0 = new JPasswordField();
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jPasswordField0, true);
      jTextComponentDestination0.removeFilteredView();
      assertEquals(true, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test3()  throws Throwable  {
      JTextArea jTextArea0 = new JTextArea();
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jTextArea0, false);
      assertEquals(false, jTextComponentDestination0.autoPositionCaret());
      
      jTextComponentDestination0.setAutoPositionCaret(true);
      assertEquals(true, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test4()  throws Throwable  {
      JEditorPane jEditorPane0 = new JEditorPane("", "");
      SearchEngine searchEngine0 = new SearchEngine(0);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jEditorPane0, searchEngine0, "X{&yP*^.xr#9 rh_(jD", true);
      filteredDestination0.addFilteredView();
      assertEquals(true, filteredDestination0.autoPositionCaret());
  }

  @Test
  public void test5()  throws Throwable  {
      JPasswordField jPasswordField0 = new JPasswordField();
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jPasswordField0, false);
      JPasswordField jPasswordField1 = (JPasswordField)jTextComponentDestination0.getJTextComponent();
      assertNotNull(jPasswordField1);
      assertEquals(false, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test6()  throws Throwable  {
      JTextField jTextField0 = new JTextField();
      SearchEngine searchEngine0 = new SearchEngine(1797);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jTextField0, searchEngine0, "", false);
      filteredDestination0.handlePrint("rzq&AYp['h");
      assertEquals("rzq&AYp['h", jTextField0.getText());
  }

  @Test
  public void test7()  throws Throwable  {
      JPasswordField jPasswordField0 = new JPasswordField();
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jPasswordField0, true);
      jTextComponentDestination0.print("");
      assertEquals(true, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test8()  throws Throwable  {
      JTextField jTextField0 = new JTextField("");
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jTextField0, false);
      jTextComponentDestination0.clear();
      assertEquals(false, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test9()  throws Throwable  {
      JPasswordField jPasswordField0 = new JPasswordField();
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jPasswordField0, true);
      jTextComponentDestination0.clear();
      assertEquals(true, jTextComponentDestination0.autoPositionCaret());
  }
}
