/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.io.PrintStreamDestination;
import java.io.PrintStream;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PrintStreamDestinationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PrintStreamDestination printStreamDestination0 = new PrintStreamDestination((PrintStream) null);
      // Undeclared exception!
      try {
        printStreamDestination0.print("");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      PrintStreamDestination printStreamDestination0 = new PrintStreamDestination((PrintStream) null);
      printStreamDestination0.clear();
  }

  @Test
  public void test2()  throws Throwable  {
      PrintStreamDestination printStreamDestination0 = new PrintStreamDestination((PrintStream) null);
      PrintStream printStream0 = printStreamDestination0.getPrintStream();
      assertNull(printStream0);
  }

  @Test
  public void test3()  throws Throwable  {
      PrintStreamDestination printStreamDestination0 = new PrintStreamDestination((PrintStream) null);
      printStreamDestination0.setPrintStream((PrintStream) null);
  }
}
