/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.io.FilteredDestination;
import ghm.follow.io.JTextComponentDestination;
import ghm.follow.io.OutputDestination;
import ghm.follow.search.SearchEngine;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestFilterableOutputDestination {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JFormattedTextField jFormattedTextField0 = new JFormattedTextField((JFormattedTextField.AbstractFormatter) null);
      SearchEngine searchEngine0 = new SearchEngine((-1503));
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jFormattedTextField0, searchEngine0, "-", false);
      filteredDestination0.addView((OutputDestination) filteredDestination0);
      // Undeclared exception!
      try {
        filteredDestination0.notifyViews("-");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class sun.font.FontScaler
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      SearchEngine searchEngine0 = new SearchEngine(0);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) null, searchEngine0, (String) null, false);
      filteredDestination0.removeView((OutputDestination) filteredDestination0);
      assertEquals(false, filteredDestination0.autoPositionCaret());
  }

  @Test
  public void test2()  throws Throwable  {
      SearchEngine searchEngine0 = new SearchEngine(0);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) null, searchEngine0, (String) null, false);
      filteredDestination0.addView((OutputDestination) filteredDestination0);
      filteredDestination0.removeView((OutputDestination) filteredDestination0);
      assertEquals(false, filteredDestination0.autoPositionCaret());
  }

  @Test
  public void test3()  throws Throwable  {
      SearchEngine searchEngine0 = new SearchEngine(0);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) null, searchEngine0, (String) null, false);
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) null, true);
      jTextComponentDestination0.addView((OutputDestination) filteredDestination0);
      jTextComponentDestination0.removeView((OutputDestination) jTextComponentDestination0);
      assertEquals(true, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test4()  throws Throwable  {
      JTextField jTextField0 = new JTextField("");
      SearchEngine searchEngine0 = new SearchEngine(548);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jTextField0, searchEngine0, "", true);
      filteredDestination0.print("");
      assertEquals(true, filteredDestination0.autoPositionCaret());
  }
}
