/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.io.FilteredDestination;
import ghm.follow.io.JTextComponentDestination;
import ghm.follow.search.SearchEngine;
import javax.swing.JFormattedTextField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Document;
import javax.swing.text.JTextComponent;
import javax.swing.text.StyledDocument;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestJTextComponentDestination {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) null, true);
      boolean boolean0 = jTextComponentDestination0.autoPositionCaret();
      assertEquals(true, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      JFormattedTextField jFormattedTextField0 = new JFormattedTextField();
      SearchEngine searchEngine0 = new SearchEngine(1);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jFormattedTextField0, searchEngine0, "", false);
      filteredDestination0.setJTextComponent((JTextComponent) jFormattedTextField0);
      assertEquals(false, filteredDestination0.autoPositionCaret());
  }

  @Test
  public void test2()  throws Throwable  {
      JTextField jTextField0 = new JTextField();
      SearchEngine searchEngine0 = new SearchEngine(0);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jTextField0, searchEngine0, "", true);
      filteredDestination0.removeFilteredView();
      assertEquals(true, filteredDestination0.autoPositionCaret());
  }

  @Test
  public void test3()  throws Throwable  {
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) null, true);
      jTextComponentDestination0.setAutoPositionCaret(true);
      assertEquals(true, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test4()  throws Throwable  {
      SearchEngine searchEngine0 = new SearchEngine(0);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) null, searchEngine0, "", true);
      filteredDestination0.addFilteredView();
      assertEquals(true, filteredDestination0.autoPositionCaret());
  }

  @Test
  public void test5()  throws Throwable  {
      JFormattedTextField jFormattedTextField0 = new JFormattedTextField();
      SearchEngine searchEngine0 = new SearchEngine(1);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jFormattedTextField0, searchEngine0, "", false);
      JFormattedTextField jFormattedTextField1 = (JFormattedTextField)filteredDestination0.getJTextComponent();
      assertNotNull(jFormattedTextField1);
      assertEquals(false, filteredDestination0.autoPositionCaret());
  }

  @Test
  public void test6()  throws Throwable  {
      DefaultStyledDocument defaultStyledDocument0 = new DefaultStyledDocument();
      JTextPane jTextPane0 = new JTextPane((StyledDocument) defaultStyledDocument0);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jTextPane0, (SearchEngine) null, "BadLocationExcepto in JTextPaneDestination", false);
      filteredDestination0.handlePrint("BadLocationExcepto in JTextPaneDestination");
      assertEquals(42, defaultStyledDocument0.getLength());
      assertEquals("BadLocationExcepto in JTextPaneDestination", jTextPane0.getText());
  }

  @Test
  public void test7()  throws Throwable  {
      JTextPane jTextPane0 = new JTextPane();
      DefaultStyledDocument defaultStyledDocument0 = (DefaultStyledDocument)jTextPane0.getDocument();
      JTextArea jTextArea0 = new JTextArea((Document) defaultStyledDocument0);
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jTextArea0, true);
      jTextComponentDestination0.print("");
      assertEquals(true, jTextComponentDestination0.autoPositionCaret());
  }

  @Test
  public void test8()  throws Throwable  {
      JFormattedTextField jFormattedTextField0 = new JFormattedTextField();
      SearchEngine searchEngine0 = new SearchEngine(1);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) jFormattedTextField0, searchEngine0, "", false);
      filteredDestination0.clear();
      assertEquals(false, filteredDestination0.autoPositionCaret());
  }

  @Test
  public void test9()  throws Throwable  {
      JFormattedTextField jFormattedTextField0 = new JFormattedTextField();
      JTextComponentDestination jTextComponentDestination0 = new JTextComponentDestination((JTextComponent) jFormattedTextField0, true);
      jTextComponentDestination0.clear();
      assertEquals(true, jTextComponentDestination0.autoPositionCaret());
  }
}
