/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.io.FilteredDestination;
import ghm.follow.search.SearchEngine;
import javax.swing.text.JTextComponent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestFilteredDestination {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SearchEngine searchEngine0 = new SearchEngine(1466);
      FilteredDestination filteredDestination0 = new FilteredDestination((JTextComponent) null, searchEngine0, (String) null, false);
      // Undeclared exception!
      try {
        filteredDestination0.print((String) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
