/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.search;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.search.LineResult;
import ghm.follow.search.WordResult;
import java.util.List;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class LineResultEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LineResult lineResult0 = new LineResult(0, (-1531), 0);
      WordResult wordResult0 = new WordResult(241, 1208, "", 0);
      lineResult0.addWord(wordResult0);
      lineResult0.addWord(wordResult0);
      assertEquals("Line 0 (242-1208,242-1208)", lineResult0.toString());
      assertEquals(241, lineResult0.getFirstWordPosition());
  }

  @Test
  public void test1()  throws Throwable  {
      LineResult lineResult0 = new LineResult(0, 0, 0);
      List<WordResult> list0 = lineResult0.getWordResults();
      assertNotNull(list0);
      assertEquals(2147483647, lineResult0.getFirstWordPosition());
      assertEquals(0, lineResult0.end);
      assertEquals(0, lineResult0.lineNumber);
      assertEquals(0, lineResult0.start);
  }

  @Test
  public void test2()  throws Throwable  {
      LineResult lineResult0 = new LineResult(0, 0, 0);
      int int0 = lineResult0.getFirstWordPosition();
      assertEquals(Integer.MAX_VALUE, int0);
      assertEquals(0, lineResult0.lineNumber);
      assertEquals(0, lineResult0.end);
      assertEquals(0, lineResult0.start);
  }

  @Test
  public void test3()  throws Throwable  {
      LineResult lineResult0 = new LineResult(0, 0, 0);
      // Undeclared exception!
      try {
        lineResult0.getWordResult(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 0, Size: 0
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      LineResult lineResult0 = new LineResult(0, 0, 0);
      String string0 = lineResult0.toString();
      assertEquals(2147483647, lineResult0.getFirstWordPosition());
      assertEquals(0, lineResult0.end);
      assertNotNull(string0);
      assertEquals("Line 0", string0);
      assertEquals(0, lineResult0.start);
  }

  @Test
  public void test5()  throws Throwable  {
      LineResult lineResult0 = new LineResult(0, (-1531), 0);
      WordResult wordResult0 = new WordResult(241, 1208, "", 0);
      lineResult0.addWord(wordResult0);
      String string0 = lineResult0.toString();
      assertEquals(241, lineResult0.getFirstWordPosition());
      assertEquals("Line 0 (242-1208)", string0);
  }

  @Test
  public void test6()  throws Throwable  {
      LineResult lineResult0 = new LineResult(0, (-1531), 0);
      WordResult wordResult0 = new WordResult(241, 1208, "", 0);
      lineResult0.addWord(wordResult0);
      assertEquals(241, lineResult0.getFirstWordPosition());
      
      WordResult wordResult1 = new WordResult(0, 0, "", 1208);
      lineResult0.addWord(wordResult1);
      String string0 = wordResult0.parent.toString();
      assertEquals("Line 0 (242-1208,)", string0);
  }
}
