/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.event;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ghm.follow.config.FollowAppAttributes;
import ghm.follow.event.WindowTracker;
import ghm.follow.systemInterface.SystemInterface;
import java.awt.event.WindowEvent;
import javax.swing.JTabbedPane;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestWindowTracker {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JTabbedPane jTabbedPane0 = new JTabbedPane();
      WindowTracker windowTracker0 = new WindowTracker((FollowAppAttributes) null, jTabbedPane0, (SystemInterface) null);
      // Undeclared exception!
      try {
        windowTracker0.windowClosed((WindowEvent) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
